### ISSUE TITLE
Build failure with hpack 0.29

### ISSUE THREAD

**Issue by jkachmar** [NixOS/cabal2nix#359]
`cabal2nix` fails to build with `hpack-0.29` with the following error:

```
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs:205:12: error:
    • The constructor ‘Hpack.DecodeResult’ should have 4 arguments, but has been given 3
    • In the pattern: Hpack.DecodeResult pkg' _ _
      In the pattern: Right (Hpack.DecodeResult pkg' _ _)
      In a case alternative:
          Right (Hpack.DecodeResult pkg' _ _)
            -> do let hpackOutput = ...
                      ....
                  case
                      runParseGenericPackageDescription "<hpack output>" hpackOutput
                  of
                    Left msg -> liftIO $ ...
                    Right pkg
                      -> MaybeT $ return $ Just $ (,) True $ setCabalFileHash hash pkg
    |
205 |     Right (Hpack.DecodeResult pkg' _ _) -> do
    |   
```
